### ISSUE TITLE
Cannot add feed containing a comma in the url (bug)

### ISSUE THREAD

**Issue by GLLM** [readerself/readerself#18]
I tried to add :
http://www.tomshardware.com/fr/feeds/rss2/presence-pc,1-1.xml

Error : 
A feed could not be found at http://www.tomshardware.com/fr/feeds/rss2/presence-pc,1-1.xml. This does not appear to be a valid RSS or Atom feed.

I know this feed is valid, I use it in another app ;)

Cheers,

**Comment by project29k** [comment]
It's valid now
