### ISSUE TITLE
Actions button in open items not ideally placed (enhancement)

### ISSUE THREAD

**Issue by GLLM** [readerself/readerself#36]
Hello,

I believe the mark as read-unread / share / favorite buttons should be place at the bottom of the expanded item.
Indeed, you decide once you have read the item what you want to to with it, and not a the beginning of your reading.
Placing those at the bottom right side would be better.

I manage to change this in item.php, but my problem is that the buttons, when item is collapse, do not show anymore (the mark as read/unread for instance).

Given the present codeline, I'm not sure what would be better to still have buttons in the collapse mode, and the buttons at the right bottom in the expanded mode.

Any thought ?

GLLM

**Comment by project29k** [comment]
You can check the new version (buttons at the bottom)
