### ISSUE TITLE
Question/Feature-Request: Use current time as timestamp for shared items

### ISSUE THREAD

**Issue by nasser-torabzade** [readerself/readerself#53]
When I share an item, readerself inserts it into shared items public feed, and uses the time which  that item was originally published as the time stamp, so recently shared items are not always on top of my public feed. Is it possible to use current time (time which article was shared) as timestamp for shared items in public feed?
thanks.

**Comment by project29k** [comment]
it's done, only in public feed

**Comment by nasser-torabzade** [comment]
thanks, my bad.
