### ISSUE TITLE
Feature-Request: Transfer images to localhost

### ISSUE THREAD

**Issue by nasser-torabzade** [readerself/readerself#54]
Hi,
I need Readerself to transfer images inside articles to a sub-directory in it's installation path, and use the transferred version of them. Is it possible for you to add this feature?
thanks.

**Comment by nasser-torabzade** [comment]
I'm planning to add this feature myself, can you guide me where to start? I'm new to code igniter.
thanks.

**Comment by project29k** [comment]
Hi

With SimplePie you can define an image handler
http://simplepie.org/wiki/reference/simplepie/set_image_handler

See
/thirdparty/simplepie/SimplePie/Sanitize.php
line 300

And
/application/controllers/refresh.php
line 164
to add $sp_feed->set_image_handler('handler_image.php', 'image');
