### ISSUE TITLE
Setting up cronjob on a shared host

### ISSUE THREAD

**Issue by nasser-torabzade** [readerself/readerself#55]
Hi,
I've installed readerself on a shared host running cpanel with no command line access, and in cronjob section of cpanel I've tried following commands, but none of them worked.
```
cd /home/myUserName/public_html/apps/reader && php index.php refresh items
php /home/myUserName/public_html/apps/reader/index.php refresh items
/usr/bin/php /home/myUserName/public_html/apps/reader/index.php refresh items
```
Can you create a update script that can be executed by a HTTP GET request to be executed by wget?

**Comment by project29k** [comment]
Hi

You can use the same script
http://domain.com/apps/reader/refresh/items

**Comment by nasser-torabzade** [comment]
perfectly worked, thanks.
