### ISSUE TITLE
After succesfull install no login possible

### ISSUE THREAD

**Issue by Wanabo** [readerself/readerself#56]
Installed readerself in a directory like so: example.com/rs
database.php edited options for sqlite.
$db['default']['hostname'] = 'sqlite:application/database/readerself.sqlite';
$db['default']['username'] = '';
$db['default']['password'] = '';
$db['default']['database'] = '';
$db['default']['dbdriver'] = 'pdo';

Then in the setup page entered my details, but after that I am redirected to example.com/rs/register. Even pressing the login button redirects me to example.com/rs/register.

Setup: KVM VPS, Nginx/Apache, DirectAdmin.

**Comment by project29k** [comment]
I had not tried the sqlite version for a long time
The database is ok but there is a strange error with queries
(the user is saved on setup, but no result when counting members, so you return to register)

For now I don't have the solution

**Comment by Wanabo** [comment]
Thanks, I've tried the database setup. But $db['default']['dbprefix'] = ''; is not working. I had it setup with $db['default']['dbprefix'] = 'rs_'; but the installer did not create a dbprefix. So it messed up my database. :(
Removed the dbprefix and now I can log in.
I'm getting db errors though.
--------

A Database Error Occurred

Error Number: 1054

Unknown column 'itm.itm_id' in 'field list'

SELECT COUNT(DISTINCT(itm.itm_id)) AS count FROM items AS itm WHERE itm.itm_link = 'http://www.gva.be/cnt/dmf20150801_01800707/club-brugge-verwerkt-opdoffers-met-ruime-zege-tegen-kv-mechelen' OR itm.itm_link = 'http://www.gva.be/cnt/dmf20150801_01800707/club-brugge-verwerkt-opdoffers-met-ruime-zege-tegen-kv-mechelen'

Filename: /example.be/public_html/rs/libraries/Readerself_library.php

Line Number: 220
------------

Is it possible to make my personal feeds public without a login for people?

Regards.

**Comment by project29k** [comment]
You have to define a nickname in your profile
Your public profile will be at this address /member/NICKNAME
