### ISSUE TITLE
When import opml, only one folder is created

### ISSUE THREAD

**Issue by NerosTie** [readerself/readerself#60]
I imported my OPML from Freshrss with many folders but only one (the first) is created in Readerself.

**Comment by project29k** [comment]
It's fixed (see /application/controllers/Subscriptions.php)
(some problems with "num_rows" with sqlite)

https://github.com/readerself/readerself/commit/d131b998db52a7baacc3e1e98de687ed49216195

**Comment by NerosTie** [comment]
It works. Thanks :)
