### ISSUE TITLE
Suggestion: more edit options

### ISSUE THREAD

**Issue by NerosTie** [readerself/readerself#62]
![readerself](https://cloud.githubusercontent.com/assets/4572452/9199540/520a3ac2-4043-11e5-92a5-b458374bc89a.png)

This website has no links and no description. It could be great to have edit options to add them.

**Comment by NerosTie** [comment]
`php index.php refresh items` has updated everything. It's really cool!  
So, maybe these edit options are not usefull.

**Comment by project29k** [comment]
After opml import, I don't retrieve feed details

Only with refresh/items command or with manual adding subscription
