### ISSUE TITLE
The update doesn't work

### ISSUE THREAD

**Issue by NerosTie** [readerself/readerself#64]
I try to update but I got this error: 

```
Fatal error: Maximum execution time of 30 seconds exceeded in /var/www/readerself/application/controllers/Settings.php on line 187
A PHP Error was encountered

Severity: Error

Message: Maximum execution time of 30 seconds exceeded

Filename: controllers/Settings.php

Line Number: 187

Backtrace:
```

(with Nginx)

**Comment by project29k** [comment]
I set time to 120 seconds
https://github.com/readerself/readerself/commit/e7155ec83bc08a5cbfe0679c66bba7f1eb1e4b90

On my Mac it takes about 20-25 sec.
On my Debian virtual machine it takes about 5-10 sec.
(download zip, extract all files and load database queries if any)

**Comment by NerosTie** [comment]
It works now, thanks :+1:
