### ISSUE TITLE
database.php and readerself_config.php missing

### ISSUE THREAD

**Issue by markfrancis905** [readerself/readerself#66]
Hello,

I'm installing readerself on a fresh centos 7 box.

I'm getting multiple files missing when loading the setup:

/application/config/database.php
File missing
/application/config/readerself_config.php
File missing

...But I can't find any examples of how these files should be structured. I plan to use a mysql database. I've added the following to my php.ini:

extension=pdo.so
extension=pdo_mysql.so

Any pointers would be appreciated, thanks.

**Comment by project29k** [comment]
Hi

The directory /application/config must be writable (chmod 755)
The setup script generate empty file if it's ok, after submit the files are filled with parameters

To use mysql you need to add
extension=mysqli.so

**Comment by markfrancis905** [comment]
Great, that fixed that initial problem.

For anyone else reading, I also had "Fatal error: Call to undefined function mb_detect_encoding()" when trying to add a feed. This was resolved by running:

yum install php-gd php-mbstring

The second problem I can't solve is when running the update cron manually, I see this:

[root@rss readerself]# php index.php refresh items
PHP Warning:  Module 'mysqli' already loaded in Unknown on line 0
PHP Warning:  Module 'PDO' already loaded in Unknown on line 0
PHP Warning:  Module 'pdo_mysql' already loaded in Unknown on line 0

##################################
debug
##################################
date: 2015-08-16 17:07:49
elapsed_time: 0.2366
memory_get_peak_usage: 6 082 552
memory_get_usage: 5 486 064
##################################
errors (0)
##################################
queries (7)
###
SELECT stg.* FROM settings AS stg WHERE stg.stg_is_global = 1 GROUP BY stg.stg_id ORDER BY stg.stg_code ASC
0.00045585632324218750
###
SELECT fed.* FROM feeds AS fed WHERE fed.fed_nextcrawl IS NULL OR fed.fed_nextcrawl <= '2015-08-16 17:07:49' GROUP BY fed.fed_id HAVING (SELECT COUNT(DISTINCT(sub.mbr_id)) FROM subscriptions AS sub WHERE sub.fed_id = fed.fed_id) > 0
0.00064420700073242188
###
SELECT COUNT(DISTINCT(itm.itm_id)) AS count FROM items AS itm WHERE itm.itm_link = 'http://science.slashdot.org/story/15/08/16/1215223/donald-trump-thinks-going-to-mars-would-be-wonderful-but-there-is-a-catch?utm_source=rss1.0mainlinkanon&amp;utm_medium=feed' OR itm.itm_link = 'http://science.slashdot.org/story/15/08/16/1215223/donald-trump-thinks-going-to-mars-would-be-wonderful-but-there-is-a-catch?utm_source=rss1.0mainlinkanon&utm_medium=feed'
0.00071692466735839844
###
SELECT itm.itm_datecreated FROM items AS itm WHERE itm.fed_id = '1' GROUP BY itm.itm_id ORDER BY itm.itm_id DESC LIMIT 0,1
0.00017905235290527344
###
UPDATE `feeds` SET `fed_title` = 'Slashdot', `fed_url` = 'http://slashdot.org/', `fed_link` = 'http://rss.slashdot.org/Slashdot/slashdotMain', `fed_host` = 'slashdot.org', `fed_type` = 'rss', `fed_image` = 'http://a.fsdn.com/sd/topics/topicslashdot.gif', `fed_description` = 'News for nerds, stuff that matters', `fed_lasterror` = NULL, `fed_lastcrawl` = '2015-08-16 17:07:49', `fed_nextcrawl` = NULL
WHERE `fed_id` = '1'
0.00025296211242675781
###
INSERT INTO `crawler` (`crr_time`, `crr_memory`, `crr_feeds`, `crr_datecreated`) VALUES (0.19687700271606, 6082552, 1, '2015-08-16 17:07:49')
0.00020909309387207031
###
OPTIMIZE TABLE categories, authors, tags, tags_items, connections, enclosures, favorites, feeds, folders, history, items, members, share, subscriptions
0.00256896018981933594
##################################

A PHP Error was encountered

Severity: Core WarningMessage:  Module 'pdo_mysql' already loadedFilename: UnknownLine Number: 0

Backtrace:
			
			
			
			
(this is empty)

**Comment by project29k** [comment]
The modules are probably declared twice: in global configuration (php.ini) and module configuration ("module".ini)

When you use yum install php-mysqli, the module is loaded with his configuration, no need to add extension declaration in php.ini (I use Debian but I think it's same)

Keep only one extension declaration by module
(and you can remove pdo_mysql if you don't have other application using it)

**Comment by markfrancis905** [comment]
Great, that's it all working now, thanks a lot!
