### ISSUE TITLE
Add Wallabag/Read-it-later and Shaarli

### ISSUE THREAD

**Issue by NerosTie** [readerself/readerself#67]
Is it possible to add Wallabag/Read-it-later and Shaalit in the sharing choices?

It could be great!

**Comment by project29k** [comment]
Wallabag done

**Comment by project29k** [comment]
Shaarli done

**Comment by NerosTie** [comment]
Very fast! And it works :)  

Thanks!

**Comment by nicolabricot** [comment]
Thanks for adding the Shaarli share :+1: !
