### ISSUE TITLE
Reeder (iPhone app) crashes when syncing with Fever API

### ISSUE THREAD

**Issue by mikkelnl** [readerself/readerself#73]
Not sure what I can do to debug, but when I set my installation in Reeder app, Reeder will crash when I try to sync.

**Comment by project29k** [comment]
Do you have access to your web server log?

**Comment by pawi** [comment]
I experience similar crashes but with Reeder on OSX, i assume that the share the same sync engine. I used Fever till today and switched to readerself. Initial syncing worked with some youtube feeds but after adding some regular feeds Reeder crashes repeatedly on sync with readerself. I reset Reeder (deleting library for fresh start) and reconfigure Reeder again just to be sure. Due the crash i tried the ReadKit Trail and ReadKit sync works, i think that the sync engine from ReadKit is more forgiving than Reeder.

Due the fact that it initial worked fine (about 50 feeds) and the crashes appears only after adding some more feeds i think it has to do with the amount of feeds or with the feeds specifics like special characters (umlaut or accent). 

The webserver logs for one sync request:
`
"POST /readerself/fever/?api&unread_item_ids HTTP/1.1" 200 702 "-" "Reeder/3000.09.01 CFNetwork/760.5.1 Darwin/15.5.0 (x86_64)"
"POST /readerself/fever/?api&groups HTTP/1.1" 200 1064 "-" "Reeder/3000.09.01 CFNetwork/760.5.1 Darwin/15.5.0 (x86_64)"
"POST /readerself/fever/?api&feeds HTTP/1.1" 200 6272 "-" "Reeder/3000.09.01 CFNetwork/760.5.1 Darwin/15.5.0 (x86_64)"
"POST /readerself/fever/?api&saved_item_ids HTTP/1.1" 200 592 "-" "Reeder/3000.09.01 CFNetwork/760.5.1 Darwin/15.5.0 (x86_64)"
"POST /readerself/fever/?api&items&with_ids=398%2C652%2C768%2C869%2C879%2C922%2C923%2C1544%2C1559 HTTP/1.1" 200 4578 "-" "Reeder/3000.09.01 CFNetwork/760.5.1 Darwin/15.5.0 (x86_64)"
`

After or during the last line the app crashes. Following the data from the last API call:

`
{  
   "auth":0,
   "api_version":2,
   "date":"2016-05-24 10:22:41",
   "elapsed_time":"0.0108",
   "memory_get_peak_usage":"3 483 792",
   "memory_get_usage":"3 366 584",
   "errors_count":1,
   "errors":[  
      "E_NOTICE | Undefined index: api_key | \/home\/[username]\/website\/public\/readerself\/application\/controllers\/Fever.php | 13"
   ],
   "queries_count":4,
   "queries":[  
      {  
         "query":"SELECT stg.* FROM settings AS stg WHERE stg.stg_is_global = 1 GROUP BY stg.stg_id ORDER BY stg.stg_code ASC",
         "time":"0.00012302398681640625"
      },
      {  
         "query":"SELECT mbr.* FROM members AS mbr WHERE mbr.mbr_id = 1 GROUP BY mbr.mbr_id",
         "time":"0.00027203559875488281"
      },
      {  
         "query":"SELECT cnt.* FROM connections AS cnt WHERE cnt.mbr_id = 1 AND token_connection IS NOT NULL AND token_connection = '[a token]' GROUP BY cnt.cnt_id",
         "time":"0.00023698806762695312"
      },
      {  
         "query":"SELECT tok.mbr_id FROM tokens AS tok WHERE tok.tok_type = 'fever' AND tok.tok_value = NULL AND tok.tok_sandbox = 0 GROUP BY tok.tok_id",
         "time":"0.00009989738464355469"
      }
   ]
}
`

**Comment by project29k** [comment]
I made a new release 3.5.3 to fix Fever

String "Unknown" instead of boolean "false" when author is null
