### ISSUE TITLE
Feature request: Pinboard integration

### ISSUE THREAD

**Issue by herrbischoff** [readerself/readerself#76]
Being a dedicated pinboard.in user, I'd appreciate the integration with the service. I have something quite simple in mind: whenever I star/bookmark a post, it gets pushed to Pinboard for safe-keeping.

Thanks for your consideration!

**Comment by project29k** [comment]
It's available now

Settings / Update => 3.5.2
Settings / Goodies => Connect to Pinboard

star / share => add to Pinboard
unstar / unshare => delete from Pinboard

**Comment by herrbischoff** [comment]
@project29k: Wow, thanks a lot! :) I have just tried it and it works beautifully.
