### ISSUE TITLE
Error when i try to update database

### ISSUE THREAD

**Issue by Voronwe007** [readerself/readerself#77]
hi,

i try to run 

Fatal error: Call to undefined function mysqli_init() in /volume1/web/readerself/system/database/drivers/mysqli/mysqli_driver.php on line 126

A PHP Error was encountered

Severity: ErrorMessage:  Call to undefined function mysqli_init()Filename: /volume1/web/readerself/system/database/drivers/mysqli/mysqli_driver.phpLine Number: 126

Do you need more information ?

**Comment by project29k** [comment]
Hi

It's weird, this is a basic function available in PHP 5 and 7
http://php.net/manual/en/mysqli.init.php

What are your versions of PHP and MySQL?
You must have MySQL 4.1 and above to use mysqli

If not, you can edit /application/config/database.php
and change "dbdriver" to "mysql" (not "mysql**i**")
But mysql extension is deprecated since PHP 5.5 and removed in PHP 7

**Comment by Voronwe007** [comment]
thanks for the quick reply,

I use Mariadb 5.5 and Php 5.6. I just want to tell you i'm a noob.
I will try to  edit what you said, i will come back to you

NOTE: I install your reader on a synology

**Comment by Voronwe007** [comment]
well thanks, but it doesn't work i have got this error now :
Fatal error: Call to undefined function mysql_connect() in /volume1/web/readerself/system/database/drivers/mysql/mysql_driver.php on line 136
A PHP Error was encountered

I will install again your reader, i must have done an error somewhere...  Here the step i have done so far:
1 download and unzip "readerself-master" on the web directory
2 change owner of the file to http
3 create database and a user 
4 go to the setup web page like you said 
5 launch the task scheduler off the synology service (= cron) to update my feeds

**Comment by Voronwe007** [comment]
Well i did a fresh install and now i have got this problem : 

Database error: Une erreur de la base de donnÃ©es s'est produite.
	could not find driver
	Filename: core/Hooks.php
	Line Number: 247

**Comment by Voronwe007** [comment]
it was my fault, i use the wrong command php instead of php56 but it's not working either... i will continue to search and post the respond here if i find it.
