### ISSUE TITLE
cannot Add to cron : php index.php refresh items with space

### ISSUE THREAD

**Issue by hjp910** [readerself/readerself#79]
Hi

In some host (eg:byethost) , cannot add to cron job "index.php refresh items" with space

it seems must use one line url command ,
but I use  http://***********/readerself/index.php?refresh&items
it still cannot work ,
How to auto refresh items (hourly)?
or could it refresh items by php code ?
How to do it ?

**Comment by project29k** [comment]
Hi

Try url http://***********/readerself/refresh/items

**Comment by hjp910** [comment]
Yes!
It works very good!
Thanks

**Comment by hjp910** [comment]
Yes!
It works very good!
Thanks

2016-06-05 11:41 GMT+08:00 Stéphane Dion <notifications@github.com>:
