### ISSUE TITLE
SQL Migrations system : how it works ?

### ISSUE THREAD

**Issue by JimmyJanisson** [readerself/readerself#80]
Hello,
I'm a new user on this cool software that i choose for is complete set of features and especially for is ldap support. So first, let me thank you for your work.
But trying installing it, i discover that many things doesn't fit my LDAP configuration, and were annoying for final users.
So i fork that repo and i'm almost ready to submit my pull request but there still one thing i don't get : i had to add a field in the member table. I add it in the `application/database/installation-mysql.sql` and `application/database/installation-sqlite.sql` so that worked for me installing a fresh readerself. 

My question concern the update-bdd method : should i create two files under `application/database/` for mysql & sqlite like others files in that directory, or should i add my query in the files located in the root directory named `UPDATE-mysql.sql` and `UPDATE-sqlite.sql` ?

Sorry for my poor english & my unknowledge of CodeIgniter.

**Comment by project29k** [comment]
Hi

The files located in the root directory named UPDATE-mysql.sql and UPDATE-sqlite.sql were used for manual update/history. They're not up to date.

Now I use an automatic update connected with Github release
You can set files update-mysql-3.5.4.sql and update-sqlite-3.5.4.sql in /application/database directory

If it's ok I will made a new release 3.5.4 in Github

**Comment by JimmyJanisson** [comment]
Ok ! Thanks for your reactivity, i'll submit my pull request soon.
